import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import Imersao from "../assets/imersion.png";
import Button from '../components/Button';
import Input from '../components/Input';

export default function Home() {
    const [image, setImage] = useState<string>();
    const [imagePath, setImagePath] = useState<string>("");
    const [imageText, setImageText] = useState<string>("");

    function handleGenerateSticker() {
        var data = {
            imagePath,
            imageText
        }
        console.log(data);

        const request: RequestInit = {
            headers: {
                "Content-Type": "application/json"
            },
            method: "POST",
            body: JSON.stringify(data)
        }

        fetch("http://localhost:8080/image", request)
            .then(res => { return res.blob() })
            .then(blob => {
                var img = URL.createObjectURL(blob);

                setImage(img);
            })
    }

    return (
        <div className="flex h-screen py-16 items-center justify-center">
            <Head>
                <title>Imersão Alura Next.js+Java</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col w-4/12 h-full p-4 items-center rounded-xl bg-blue-100">
                <span className='flex flex-col items-center h-20'>
                    <p className='font-semibold text-3xl'>
                        Gerador de Stickers
                    </p>
                    <p className='font-normal text-xl'>
                        Imersão Alura Next.js + Java
                    </p>
                </span>
                <span className='mb-6'>
                    <Image className='rounded-xl' src={Imersao} alt="Imersão logo" width={400} height={200} />
                </span>
                <Input imagePath={imagePath} handleChangeValue={setImagePath}
                    labelText={String.fromCodePoint(Number.parseInt("0x1F449")).concat(" Insira o caminho da Imagem")} />
                <Input imagePath={imageText} handleChangeValue={setImageText}
                    labelText={String.fromCodePoint(Number.parseInt("0x1F449")).concat(" Insira o texto do Sticker")} />
                <Button text="Gerar" handleFunction={handleGenerateSticker} />
                {
                    image &&
                    <img className='rounded-xl border-2 border-slate-300' src={image} width={200} height={200} />
                }
                {
                    image &&
                    <a href={image} download={"MyStiker.png"} className={`flex items-center justify-center 
                        w-28 h-12 mt-6 mb-2 bg-blue-400 text-xl font-semibold text-white rounded-md`}>
                        Download
                    </a>
                }
            </div>
        </div>
    )
}