import Head from 'next/head';
import { useState } from 'react';
import styles from '../styles/Home.module.css';

export default function Home() {

    const [image, setImage] = useState<string>();
    const [imagePath, setImagePath] = useState<string>("");
    const [imageText, setImageText] = useState<string>("");
    const [isDownload, setDownload] = useState(false);

    function handleTest() {
        var data = {
            imagePath,
            imageText
        }

        const request: RequestInit = {
            headers: {
                "Content-Type": "application/json"
            },
            method: "POST",
            body: JSON.stringify(data)
        }

        fetch("http://localhost:8080/image", request)
            .then(res => { return res.blob() })
            .then(blob => {
                var img = URL.createObjectURL(blob);

                setImage(img);
            })

    }

    function handleDownload() {
        setDownload(true);
    }

    return (
        <div className={styles.container}>
            <Head>
                <title>Imersão Alura Next.js</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                Gerando Imagem Braba da Imersão Alura Next + Imersão Alura Java
                <br />
                <span>
                    <p>Digite o caminho da Imagem</p>
                    <input value={imagePath} onChange={e => setImagePath(e.target.value)} />
                </span>
                <span>
                    <p>Digite o caminho da Imagem</p>
                    <input value={imageText} onChange={e => setImageText(e.target.value)} />
                </span>
                <br />
                <br />
                <button onClick={handleTest}>
                    Teste Image
                </button>
                {image && <img src={image} width={200} height={200} />}
                {image && <a href={image} download={isDownload} onClick={() => handleDownload}  >Download</a>}
            </div>
        </div>
    )
}