import Lottie from "lottie-react";
import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import Imersao from "../assets/imersion.png";
import lottieLoading from "../assets/loading.json";
import Button from '../components/Button';
import Input from '../components/Input';
import generateSticker from '../utils/restClient';
import { Sticker } from '../utils/types';

export default function Home() {
    const [image, setImage] = useState<string>();
    const [imagePath, setImagePath] = useState<string>("");
    const [imageText, setImageText] = useState<string>("");
    const [textInsideImage, setTextInsideImage] = useState(false);
    const [originalSize, setOriginalSize] = useState(false);
    const [isLoading, setLoading] = useState(false);

    function handleGenerateSticker() {
        setLoading(true);
        setImage(undefined);

        var data: Sticker = {
            imagePath,
            imageText,
            textInsideImage,
            originalSize
        }

        generateSticker(data)
            .then(img => setImage(img))
            .catch(() => false)
            .finally(() => setLoading(false));
    }

    function changeStickerText(value: string) {
        if (value.length <= 15) {
            setImageText(value);
        }
    }

    return (
        <div className="flex h-screen py-14 items-center justify-center">
            <Head>
                <title>Imersão Alura Next.js+Java</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="flex flex-col w-8/12 h-full p-4 items-center rounded-xl bg-blue-100 md:w-6/12 xl:w-4/12">
                <span className='flex flex-col items-center h-20'>
                    <p className='font-semibold text-lg sm:text-2xl md:text-3xl'>
                        Gerador de Stickers
                    </p>
                    <p className='font-normal text-base sm:text-xl'>
                        Imersão Alura Next.js + Java
                    </p>
                </span>
                <span className='mb-4'>
                    <Image className='rounded-xl' src={Imersao} alt="Imersão logo" width={400} height={200} />
                </span>
                <Input imagePath={imagePath} handleChangeValue={setImagePath}
                    labelText={String.fromCodePoint(Number.parseInt("0x1F449")).concat(" Insira a URL da Imagem")} />
                <Input imagePath={imageText} handleChangeValue={changeStickerText}
                    labelText={String.fromCodePoint(Number.parseInt("0x1F449")).concat(" Insira o texto do Sticker")} />
                <div className="flex flex-col">
                    <Input isToggle handleChangeValue={() => setOriginalSize(!originalSize)} labelText="Manter Tamanho Original" />
                    <Input isToggle handleChangeValue={() => setTextInsideImage(!textInsideImage)} labelText="Texto dentro da Imagem" />
                </div>
                <Button text="Gerar" handleFunction={handleGenerateSticker} />
                {isLoading ?
                    <Lottie className="w-2/4" animationData={lottieLoading} loop autoplay />
                    :
                    <>
                        {
                            image &&
                            <img className='rounded-xl border-2 border-slate-300' src={image} width={200} height={200} />
                        }
                        {
                            image &&
                            <a href={image} download={"MyStiker.png"} className={`flex items-center justify-center 
                                w-28 h-12 mt-6 mb-2 bg-blue-400 text-xl font-semibold text-white rounded-md`}>
                                Download
                            </a>
                        }
                    </>
                }
            </div>
        </div >
    )
}